from setuptools import setup, find_packages

setup(
    name="cobl",
    version="1.0.0",
    description="Code Repository for CoBL",
    author="Uploaded: Dean Hazineh",
    author_email="dhazineh@g.harvard.edu",
    packages=find_packages(),
    python_requires=">=3.10,<3.11",
    install_requires=[
        "diffusers==0.34.0",
        "einops==0.7.0",
        "h5py==3.11.0",
        "kornia==0.8.1",
        "lightning-utilities==0.14.3",
        "loralib==0.1.2",
        "matplotlib==3.8.4",
        "natsort==8.4.0",
        "numpy==1.26.4",
        "omegaconf==2.3.0",
        "open_clip_torch==2.32.0",
        "pillow==11.3.0",
        "pytorch-lightning==2.5.2",
        "requests==2.32.4",
        "tokenizers==0.21.2",
        "torch==2.7.1",
        "torchaudio==2.7.1",
        "torchmetrics==1.7.4",
        "torchvision==0.22.1",
        "tqdm==4.66.2",
        "transformers==4.53.2",
    ],
)
